name: Pedidos CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'LanchoneteDaRua.Ms.Pedidos.sln'

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: dotnet test /p:Configuration=$BUILD_CONFIG --no-build --verbosity normal

    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Begin SonarQube scan
      run: dotnet sonarscanner begin /k:"../../test/LanchoneteDaRua.Ms.Pedidos.Tests" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="YourSonarQubeUrl"

    - name: Build and analyze
      run: dotnet build --no-restore

    - name: End SonarQube scan
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Check coverage
      run: |
        COVERAGE=$(coverlet LanchoneteDaRua.Ms.Pedidos.Tests.dll --target "dotnet" --targetargs "test LanchoneteDaRua.Ms.Pedidos.sln --no-build" --format opencover | grep "Total" | awk '{print $4}')
        if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          echo "Code coverage is less than 80%"
          exit 1
        fi

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: lanchonete-da-rua-pedidos
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t ${ECR_REPOSITORY}:latest .
        docker tag ${ECR_REPOSITORY}:latest ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_REGISTRY}
        docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: pedidos
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: pedido-service
        cluster: lanchonete-da-rua-app
        wait-for-service-stability: true